// @ts-nocheck
"use client";
import TextEditor from "@/components/static/textEditor";
import { useState, useEffect } from "react";
import Image from "next/image";
import { useRouter } from "@bprogress/next/app";
import { useUser } from "@clerk/nextjs";
import { SpringModal } from "@/components/ui/spring-model";
import axios from "axios";
import { Skeleton } from "@/components/ui/skeleton";
import { useLoader } from "@/components/ui/Loader";
import { toast } from "react-toastify";

const bios = [
  "Tech enthusiast by day, Netflix marathoner by night. Solving problems one line of code at a time while trying to keep my houseplant alive.",
  "Just a human doing human things. Part-time superhero, full-time coffee addict. #Adulting",
  "Looking for someone who appreciates puns, bad jokes, and spontaneous dance parties in the kitchen. Swipe right if you can handle sarcasm and movie marathons.",
  "Freelance writer and serial comma enthusiast. Turning caffeine into content and typos into triumphs.",
  "Pro gamer and snack enthusiast. Here to save the virtual world one respawn at a time. Noob-friendly.",
  "Gym rat with a side of nachos. Lifting weights and spirits since 2010. Cheat day is every day.",
  "Coloring outside the lines since birth. Turning coffee stains into art and doodles into masterpieces.",
  "Explorer of places and cuisines. Collecting passport stamps and mosquito bites since 2015. Wander often, wonder always.",
  "Mom of two, master of none. Balancing bedtime stories and laundry piles with a touch of humor and a lot of caffeine.",
  "I'm a dog, but don't let that fool you. I have a PhD in fetching and a master's in belly rubs. Woof!",
];

const getRandomBio = () => {
  const randomIndex = Math.floor(Math.random() * bios.length);
  return bios[randomIndex];
};

export default function Page() {
  const { isSignedIn, isLoaded, user: newUser } = useUser();
  const { showLoader, hideLoader } = useLoader();
  const userId = newUser?.id;

  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);
  const [imagePreview, setImagePreview] = useState();
  const [user, setUser] = useState({});
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(`/api/user/${userId}`);
        setLoading(true);
        if (!res.ok) throw new Error("Network response was not ok");
        const userData = await res.json();
        setUser(userData.user);
        setImagePreview(
          userData.user.profile_image_url
            ? userData.user.profile_image_url
            : `https://eu.ui-avatars.com/api/?name=${userData.user.first_name}+${userData.user.last_name}&size=250`,
        );

        if (!userData.user.bio) {
          setText(getRandomBio());
          setIsAutoGenerated(true);
        } else {
          setText(userData.user.bio);
        }

        setLoading(false);

        if (!isSignedIn) {
          router.push("/sign-in");
        }
      } catch (error) {
        console.error("Fetch error:", error);
      }
    };

    fetchData();
  }, [userId, router, isSignedIn]);

  function deleteProfile() {
    setIsOpen(true);
  }

  async function updateProfile() {
    setLoading(true);
    showLoader();

    try {
      // Upload image if a new file is selected
      let uploadedImageUrl = user.profile_image_url || null;
      if (selectedFile && userId) {
        const formData = new FormData();
        formData.append("file", selectedFile);
        formData.append("userId", userId);

        const response = await axios.post(`/api/user-upload-image`, formData);
        uploadedImageUrl = response.data.url; // assume API returns uploaded URL
      }

      // Update user profile with bio and uploaded image URL
      await fetch(`/api/user/${userId}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ...user,
          bio: text,
          profile_image_url: uploadedImageUrl,
        }),
      });

      toast.success("Profile updated successfully!");
    } catch (error) {
      console.error("Error updating profile:", error);
      toast.error("Failed to update profile.");
    } finally {
      setLoading(false);
      hideLoader();
    }
  }

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUser((prev) => ({ ...prev, [name]: value }));
  };

  const handleEmailNotificationsChange = (e) => {
    const isChecked = e.target.checked;
    setUser((prevUser) => ({
      ...prevUser,
      emailNotifications: isChecked,
    }));
  };

  const handleCourseUpdateNotificationsChange = (e) => {
    const isChecked = e.target.checked;
    setUser((prevUser) => ({
      ...prevUser,
      courseUpdateNotifications: isChecked,
    }));
  };

  const handleCoursePurchaseNotificationsChange = (e) => {
    const isChecked = e.target.checked;
    console.log(isChecked);
    setUser((prevUser) => ({
      ...prevUser,
      coursePurchaseNotifications: isChecked,
    }));
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    setSelectedFile(file);

    if (file) {
      const previewURL = URL.createObjectURL(file);
      setImagePreview(previewURL); // show preview immediately
    }
  };

  const handleUploadClick = () => {
    document.getElementById("imageUpload").click();
  };

  const handleFileUpload = async () => {
    console.log("Uploading file:", selectedFile);
    if (selectedFile && userId) {
      const formData = new FormData();
      formData.append("file", selectedFile);
      formData.append("userId", userId);

      try {
        const response = await axios.post(`/api/user-upload-image`, formData);

        console.log("File uploaded successfully:", response.data);
      } catch (error) {
        console.error("Error uploading file:", error);
      }
    }
  };

  return (
    <section className="my-12 grid bg-customWhite px-4 text-black dark:bg-[#191919] dark:text-white md:grid-cols-2 md:px-12">
      <SpringModal isOpen={isOpen} setIsOpen={setIsOpen} />
      <div>
        <div>
          <p className="font-Monument text-2xl">My Account</p>
          <form action="" className="my-6 flex flex-col gap-5">
            <div className="flex gap-7">
              <input
                title="hidden"
                type="file"
                name="imageUpload"
                accept="image/*"
                id="imageUpload"
                className="hidden"
                onChange={handleFileChange}
              />
              {loading ? (
                <Skeleton className="h-24 w-44 cursor-pointer rounded-full bg-[#898989] object-cover md:h-52 md:w-52" />
              ) : (
                <Image
                  src={imagePreview as string}
                  alt="Profile Image"
                  className="size-[150px] cursor-pointer rounded-full object-cover"
                  onClick={handleUploadClick}
                  width={150}
                  height={150}
                />
              )}
              <div className="flex flex-col justify-between">
                <h3 className="font-Monument text-2xl">Profile Photo</h3>
                <p className="text-lg font-light">
                  We recommend an image of at least 400x400.
                  <br />
                  Gifs work too 🙌
                </p>
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <label htmlFor="firstName">First Name</label>
              <input
                value={user ? user.first_name || "" : ""}
                id="firstName"
                name="first_name"
                type="text"
                placeholder="First Name"
                className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
                onChange={handleChange}
              />
            </div>
            <div className="flex flex-col gap-2">
              <label htmlFor="lastName">Last Name</label>
              <input
                value={user ? user.last_name || "" : ""}
                id="lastName"
                name="last_name"
                type="text"
                placeholder="Last Name"
                className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
                onChange={handleChange}
              />
            </div>
            {/* <div className="flex flex-col gap-2">
              <label htmlFor="Email">Email</label>
              <input
                value={user ? user.email || "" : ""}
                disabled 
                id="Email"
                name="email"
                type="email"
                placeholder="Email Address"
                className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
                onChange={handleChange}
              />
            </div> */}
            <div className="flex flex-col gap-2">
              <label htmlFor="">Bio</label>
              {isAutoGenerated && (
                <p className="italic text-red-400">Auto Generated !</p>
              )}
              <TextEditor text={text} setText={setText} />
            </div>
          </form>
        </div>
      </div>
      <div className="flex flex-col gap-5 border-t pt-4 md:ml-12 md:border-l md:border-t-0 md:pl-12 md:pt-0">
        <h3 className="font-Monument text-2xl">Social Account</h3>
        <div className="flex flex-col gap-4 border-b pb-6">
          <div className="flex flex-col gap-2">
            <label htmlFor="Instagram">Instagram</label>
            <input
              value={user ? user.instagram || "" : ""}
              id="Instagram"
              name="instagram"
              type="text"
              placeholder="Enter your Instagram handle"
              className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
              onChange={handleChange}
            />
          </div>
          <div className="flex flex-col gap-2">
            <label htmlFor="Twitter">Twitter</label>
            <input
              value={user ? user.twitter || "" : ""}
              id="Twitter"
              name="twitter"
              type="text"
              placeholder="Enter your Twitter handle"
              className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
              onChange={handleChange}
            />
          </div>
          <div className="flex flex-col gap-2">
            <label htmlFor="Facebook">Facebook</label>
            <input
              value={user ? user.facebook || "" : ""}
              id="Facebook"
              name="facebook"
              type="text"
              placeholder="Enter your Facebook handle"
              className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
              onChange={handleChange}
            />
          </div>
          <div className="flex flex-col gap-2">
            <label htmlFor="Website">Website</label>
            <input
              value={user ? user.website || "" : ""}
              id="Website"
              name="website"
              type="text"
              placeholder="Enter your website"
              className="w-full border border-black bg-transparent p-2 focus:outline-none dark:border-[#333333]"
              onChange={handleChange}
            />
          </div>
        </div>
        <div className="flex flex-col gap-5 border-b pb-6">
          <h3>Notifications</h3>
          <div className="flex flex-col gap-5">
            <label className="inline-flex cursor-pointer items-center">
              <input
                type="checkbox"
                onChange={handleEmailNotificationsChange}
                checked={user ? user.emailNotifications : false}
                className="peer sr-only"
              />
              <div className="peer relative h-6 w-11 rounded-full bg-black after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-customWhite after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800 rtl:peer-checked:after:-translate-x-full"></div>
              <span className="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">
                Email Notifications
              </span>
            </label>
            <label className="inline-flex cursor-pointer items-center">
              <input
                type="checkbox"
                checked={user ? user.courseUpdateNotifications : false}
                onChange={handleCourseUpdateNotificationsChange}
                className="peer sr-only"
              />
              <div className="peer relative h-6 w-11 rounded-full bg-black after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-customWhite after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800 rtl:peer-checked:after:-translate-x-full"></div>
              <span className="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">
                Course Updates
              </span>
            </label>
            <label className="inline-flex cursor-pointer items-center">
              <input
                type="checkbox"
                checked={user ? user.coursePurchaseNotifications : false}
                onChange={handleCoursePurchaseNotificationsChange}
                className="peer sr-only"
              />
              <div className="peer relative h-6 w-11 rounded-full bg-black after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-customWhite after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800 rtl:peer-checked:after:-translate-x-full"></div>
              <span className="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">
                Course Purchased
              </span>
            </label>
          </div>
          <div className="flex flex-col">
            <div className="flex flex-col gap-5 md:flex-row">
              <button
                onClick={updateProfile}
                className="bg-[#018DF0] px-6 py-2"
              >
                Update Profile
              </button>
              <button
                onClick={() => deleteProfile()}
                className="bg-red-500 px-6 py-2"
              >
                Delete Profile
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
